name: Sync ghpages To Gitee

on: 
  push:
   branches:
    - ghpages

jobs:
    syncghpages:
        runs-on: ubuntu-latest
        steps:
            - name: Sync ghpages to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:menglou/king-abpvnext-pro.git
                  destination-repo: git@gitee.com:zljlm/king-abpvnext-pro.git
