name: Sync To ghpages Gitee

on: 
  push:
    branches:
      - king-abpvnext-pro

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync To ghpages Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:menglou/king-abpvnext-pro.git
                  destination-repo: git@gitee.com:zljlm/king-abpvnext-pro.git
