name: Sync To Gitee

on: [push]

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:menglou/menglou.github.io.git
                  destination-repo: git@gitee.com:zljlm/menglou.github.io.git
